name: Websend
main: com.github.websend.Main
version: 4.6
description: Plug-in to enable variables-transfer to the interwebs and backwards.
author: Waterflames
api-version: 1.16
commands:
   websend:
      description: Starts communication.
      usage: |
              /<command> <arguments>
   ws:
      description: Starts communication.
      usage: |
              /<command> <arguments>
   wsScripts:
      description: Scripts
      usage: |
              /<command> <arguments>
permissions:
    websend:
        description: Allows you to use websend
        default: op
    websend.scripts:
        description: Allows you to perform /wsScripts
        default: op